version: "3"

services:
  builder:
    image: moomesy/nodejs
    ports:
      - "20000:7001"
    volumes:
       - ./workdir:/data/workdir
       - ./logs:/root/logs
    restart: always
    environment:
       - ENTRYPOINT=yarn _start